Eds acpi 5.12 rc8
andy-shev/linux pull request #33
Opened 2021-04-24 14:41 UTC by htot

I rebased eds-acpi on 5.12-rc8 as you always do, added 3 patches from usb-next + 3 of mine dwc3 fixes. And just tested this on edison. Works nicely.

As I wrote here https://github.com/andy-shev/linux/issues/31#issuecomment-825927788 to prevent port resets we disable LPM entirely, which makes some of the patches (BESL, START_TRANSFER) redundant. I added them in case someone wants to enable LPM again, and resolve the port resets in another way.

As Thinh Nguyen wrote on [ML](https://lore.kernel.org/stable/b0b99566-a5d3-5c16-d9b1-0f743f3a6a55@gmail.com/T/):
> Nothing obvious stands out as a problem from the dwc3 driver or the
controller. I see a (port) reset after 30 seconds of inactivity, which
is a typical timeout and recovery mechanism in the upperlayer from host.

We may need to trace the host (PC) end to see why it times out. But for me, it's good enough without LPM as is.

If you would have a look a my commit messages I would be grateful!

2021-04-24 15:15 UTC, andy-shev requested changes
I left couple of comments, besides that in the commit log, add a blank line before your SoB tag along with a Fixes tag.

Fixes: 492929c54791 ("extcon: mrfld: Introduce extcon driver for Basin Cove PMIC")

PS: Crap, Fixes tag is not properly represented in the Web UI, it should follow the standard pattern: `Fixes: 12 SHA1 ("<message>")`.

Take 2:
`Fixes: 492929c54791 ("extcon: mrfld: Introduce extcon driver for Basin Cove PMIC")`

After addressing above, feel free to submit upstream. (I think my `ge2maintainer.sh` script will add my name to the Cc list)

2021-04-24 15:15 UTC, andy-shev commented on drivers/extcon/extcon-intel-mrfld.c
> +	unsigned int status;
Move it to be before `id` definition.

2021-04-24 15:15 UTC, andy-shev commented on drivers/extcon/extcon-intel-mrfld.c
> +	regmap_read(regmap, BCOVE_SCHGRIRQ1, &status);
Add a blank line here and a comment about what you are doing, e.g. "Cached status value is used for cable detection, see comments in mrfld_extcon_cable_detect(), we need to sync cached value with a real state of the hardware".

2021-04-24 15:23 UTC, andy-shev requested changes
Similar to extcon, i.e. add a blank line, before your SoB, followed by Fixes tag:
`Fixes: 066c09593454 ("usb: dwc3: pci: Enable extcon driver for Intel Merrifield")`

2021-04-24 16:36 UTC, htot commented
> Similar to extcon, i.e. add a blank line, before your SoB, followed by Fixes tag:
> `Fixes: 066c09593454 ("usb: dwc3: pci: Enable extcon driver for Intel Merrifield")`

I think this is for the "usb: dwc3: pci: Enable usb2-gadget-lpm-disable for Intel Merrifield" patch? (GH broke the View changes button, after I rebased. Grr).
I don't know which patch to reference here. It's not "usb: dwc3: pci: Enable extcon driver for Intel Merrifield". It's LPM in dwc3

2021-04-25 15:15 UTC, htot commented
Sent to ml, thanks for reviewing.

2021-04-25 15:15 UTC, closed without merging